name            = Common Plugin for Repository
description     = A common plugin for repository management.
version         = 1.0.0

url             = https://github.com/Akazukin-Team/Java-Common-Plugin-Repo

vendor          = Akazukin Team
vendor-url      = https://github.com/Akazukin-Team

groupId         = org.akazukin.plugin
artifactId      = common-repo

archiveBaseName = Common-Repo
